---
- name: Ansible List Variable Usage
  hosts: localhost
  gather_facts: false
  vars:
    course_name:
      - "Ansible Beginner Guide"
      - "Ansible Intermediate Guide"
      - "Ansible Advanced Guide"
    
  tasks:
    - name: Print a 'course name' variable value as per its scope
      ansible.builtin.debug:
        msg: "{{ course_name }}"

    - name: Print a course name variable value as per reference to its index - course_name[0]
      ansible.builtin.debug:
        msg: "First Course: {{ course_name[0] }}"

- name: Ansible Combining List Variables
  hosts: localhost
  vars:
    devops_courses:
      - Ansible
      - Git
      - Docker
      - Kubernetes
    cloud_courses:
      - AWS
      - Azure
      - GCP
  tasks:
    - name: Print all 'devops courses'
      ansible.builtin.debug:
        msg: "{{ devops_courses }}"

    - name: Print all 'cloud courses'
      ansible.builtin.debug:
        msg: "{{ cloud_courses }}"  

    - name: Merging all course
      ansible.builtin.set_fact:
        all_courses: "{{ devops_courses + cloud_courses }}"

    - name: Print all courses [devops + cloud] after merging
      ansible.builtin.debug:
        msg: "{{ all_courses }}"

- name: Ansible Dictionary Variable Usage
  hosts: localhost
  vars:
    course_details:
      name: "Ansible Beginner Guide"
      trainer: "Path4Cloud"
      mode: "Virtual Online"
    
  tasks:
    - name: Print a course details variable value as per its scope
      ansible.builtin.debug:
        msg: "{{ course_details }}"

    - name: Print a course details variable value as per reference to its key - course_details.name
      ansible.builtin.debug:
        msg: "Course Name: {{ course_details.name }}"

- name: Ansible List of Dictionary Variable Usage
  hosts: localhost
  vars:
    course_details:
      - name: "Ansible Beginner Guide"
        trainer: "Path4Cloud"
        mode: "Virtual Online"
      - name: "Ansible Intermediate Guide"
        trainer: "Path4Cloud"
        mode: "Virtual Online"
      - name: "Ansible Advanced Guide"
        trainer: "Path4Cloud"
        mode: "Virtual Online"
    
  tasks:
    - name: Print a course details variable value as per its scope
      ansible.builtin.debug:
        msg: "{{ course_details }}"

    - name: Print a course details variable value as per reference to its index and key - course_details[0].name
      ansible.builtin.debug:
        msg: |
          First Course Name: {{ course_details[0].name }}
          First Course Trainer: {{ course_details[0].trainer }}
          First Course Mode: {{ course_details[0].mode }}