---
- name: User creation with cleartext password
  hosts: localhost
  gather_facts: no
  
  vars:
    username: sam
    password: redhat

  tasks:

    - name: Creating a user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"
        #password: "{{ password | password_hash('sha512') }}"
        state: present
        #state: absent
