---
- name: User creation with cleartext password
  hosts: localhost
  gather_facts: no
  
  vars_files:
    - user_info.yaml

  tasks:

    - name: Creating a user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create # it will set the password only when the user is created
