---
- name: User creation with cleartext password
  hosts: localhost
  gather_facts: no
  
  vars_files:
    - user_vars.yaml

  tasks:

    - name: Creating a user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
