---
- name: Gathering Facts
  hosts: localhost
  tasks:
    - name: Display gathered facts
      ansible.builtin.debug:
        # var: ansible_facts  --> use this to display all the gathered facts
        var: ansible_facts['distribution']  # use this to display only the distribution name

    - name: Display the ansible_facts variable
      ansible.builtin.debug:
        msg: >
          Hello there! I am running on {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} and my architecture is {{ ansible_facts['architecture'] }} with root space of {{ ansible_facts['mounts'][0]['size_total'] | human_readable }}.

    - name: Display the ansible_facts variable using the 'ansible' prefix
      ansible.builtin.debug:
        msg: >
          My Ip is {{ ansible_facts.default_ipv4.address }} and my hostname is {{ ansible_facts.hostname }}.
        # ansible_default_ipv4 vs default_ipv4: In modern Ansible collections, when accessing properties inside the ansible_facts dictionary, the 'ansible_' prefix is dropped from the child keys. 