---
# Facts must be cached or gathered for centos9 first: The docker host cannot log into centos9 to read its files. If centos9 is not part of the same play run (or if you don't have Fact Caching enabled), hostvars['centos9'] will be completely empty.

# Play 1: Force Ansible to collect facts from centos9 first
- name: Pre-load facts for {{ inventory_hostname }} host
  hosts: centos9
  gather_facts: yes

# Play 2: Run your main logic on the docker host
- name: Reading custom facts from another host
  hosts: docker
  gather_facts: yes

  tasks:
    - name: Display custom fact for {{ inventory_hostname }} host
      ansible.builtin.debug:
        msg: "welcome to {{ hostvars['centos9']['ansible_local']['info']['ansible_training']['trainer'] }}"

# Play 3: checking groups and group_names
- name: Display group names for {{ inventory_hostname }} host
  hosts: docker
  gather_facts: yes

  tasks:
    - name: Display group names for {{ inventory_hostname }} host
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is part of the following groups: {{ group_names }}"

    - name: Display group names for {{ inventory_hostname }} host using hostvars
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is part of the following groups: {{ hostvars[inventory_hostname]['group_names'] }}"

    - name: Display all hosts in the 'target_node' group
      ansible.builtin.debug:
        msg: "All hosts in the 'target_node' group: {{ groups['target_node'] }}"