---
- name: Gathering packages facts
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Display gathered facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Display package facts
      ansible.builtin.debug:
        var: ansible_facts['packages']