---
- name: Learning Simple List Loop
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Ensure multiple packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - curl
        - git

    # yum/dnf module is capable of installing multiple packages in one go, but this is just to demonstrate the loop functionality.
    - name: Ensure multiple packages are installed (alternative method)
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - httpd
          - curl
          - git
