---
- name: Learning Dictionary Loop
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create multiple users with distinct groups
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.group_name }}"
      state: present
      loop:
        - { username: 'sam', group_name: 'wheel' }
        - { username: 'alice', group_name: 'developers' }
        - { username: 'bob', group_name: 'webmasters' }