---
- name: Learning with_dict as old style loop
  hosts: localhost
  gather_facts: no

  vars:
    users:
      sam:
        phone: "555-0122"
        department: "automation"
      alice:
        phone: "555-0199"
        department: "security"

  tasks:
    - name: Display user information
      ansible.builtin.debug:
        msg: "User {{ item.key }} works in {{ item.value.department }} (Ext: {{ item.value.phone }})"
      with_dict: "{{ users }}"

- name: Learning with_dict as new style loop
  hosts: localhost
  gather_facts: no

  vars:
    users:
      sam:
        phone: "555-0122"
        department: "automation"
      alice:
        phone: "555-0199"
        department: "security"

  tasks:
    - name: Display user information
      ansible.builtin.debug:
        msg: "User {{ item.key }} works in {{ item['value']['department'] }} (Ext: {{ item['value']['phone'] }}"
      loop: "{{ users | dict2items }}"