---
- name: Copying file from Master to target nodes
  hosts: target_node
  become: yes

  tasks:
    - name: Copyin the file
      ansible.builtin.copy:
        src: files/master_info.txt
        dest: /root/