---
- name: Learning fetch module
  hosts: target_node
  gather_facts: no
  
  tasks:
    - name: fetching the log file
      ansible.builtin.fetch:
        src: /var/log/messages
        dest: /tmp/{{ inventory_hostname }}.log
        flat: no