---
- name: Gather facts from target nodes
  hosts: target_node
  gather_facts: yes

- name: Deploy Dynamic Configuration Multi Style File
  hosts: localhost
  gather_facts: yes
  become: yes
   
  tasks:
    - name: Display gathered facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Rendering all the information
      ansible.builtin.template:
        src: templates/multi_type.j2
        dest: /tmp/multi_info
