---
- name: Deploy Dynamic Configuration Multi Style File
  hosts: localhost
  gather_facts: yes
  become: yes

  vars_file:
    - multi_info.yaml
    
  tasks:
    - name: Rendering all the information
      ansible.builtin.template:
        src: templates/multi_type.j2
        dest: /tmp/multi_info
